name: Backend Tests

on:
  push:
    paths:
      - 'simulated_pos/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'simulated_pos/**'
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./simulated_pos

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask flask-sqlalchemy flask-jwt-extended flask-cors pytest pytest-flask
        
    - name: Run tests
      run: |
        python -m pytest tests/ -v
